# This is a basic workflow to help you get started with Actions

name: Utterances to Notion comment


on:
  issue_comment:
    types: [created]

jobs:
  commented:
    name: commented
    if: ${{ github.event.issue }}
    runs-on: ubuntu-latest
    env:
      BEARER: ${{ secrets.BEARER }}
      COMMENT_URL: ${{ github.event.issue.comments_url }}
      HOST_URL: ${{ github.event.issue.title }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Dump GitHub context
      shell: bash
        
      run: |
        python3 run.py
      
