# This is a basic workflow to help you get started with Actions

name: Utterances to Notion comment


on:
  issue_comment:
    types: [created]

jobs:
  commented:
    name: commented
    if: ${{ github.event.issue }}
    runs-on: ubuntu-latest
    env:
      BEARER: ${{ secrets.BEARER }}
      COMMENT_URL: ${{ github.event.issue.comments_url }}
      HOST_URL: ${{ github.event.issue.title }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: Dump GitHub context
      shell: bash
        
      run: |
        pip install requests
        python3 run.py
      
