# This is a basic workflow to help you get started with Actions

name: Utterances to Notion comment


on:
  issue_comment:
    types: [created]

jobs:
  commented:
    name: commented
    if: ${{ github.event.issue }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Dump GitHub context
      env: 
        GITHUB_CONTEXT: ${{ toJson(github) }}
        COMMENT_URL: ${{ github.event.issue.comments_url }}
        HOST_URL: ${{ github.event.issue.title }}
        BEARER: ${{ secrets.BEARER }}
        
      run: python3 run.py
      
